[2023-04-11T13:48:02.760+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:47:00+00:00 [queued]>
[2023-04-11T13:48:02.777+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:47:00+00:00 [queued]>
[2023-04-11T13:48:02.778+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T13:48:02.780+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-11T13:48:02.780+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T13:48:02.802+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 13:47:00+00:00
[2023-04-11T13:48:02.809+0000] {standard_task_runner.py:55} INFO - Started process 1595 to run task
[2023-04-11T13:48:02.812+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T13:47:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpk9i85bm_']
[2023-04-11T13:48:02.814+0000] {standard_task_runner.py:83} INFO - Job 151: Subtask id_2
[2023-04-11T13:48:02.903+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:47:00+00:00 [running]> on host b518195edd5e
[2023-04-11T13:48:03.001+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T13:47:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T13:47:00+00:00
[2023-04-11T13:48:03.003+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T13:48:03.005+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T13:48:03.017+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T13:48:03.342+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-11T13:48:03.343+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-11T13:48:03.344+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-11T13:48:03.345+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-11T13:48:03.346+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-11T13:48:03.347+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-11T13:48:03.349+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-11T13:48:03.364+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-11T13:48:03.370+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T134700, start_date=20230411T134802, end_date=20230411T134803
[2023-04-11T13:48:03.392+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 151 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 1595)
[2023-04-11T13:48:03.427+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T13:48:03.455+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
