[2023-04-12T14:04:01.050+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T14:03:00+00:00 [queued]>
[2023-04-12T14:04:01.057+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T14:03:00+00:00 [queued]>
[2023-04-12T14:04:01.058+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T14:04:01.058+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-12T14:04:01.059+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T14:04:01.071+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 14:03:00+00:00
[2023-04-12T14:04:01.075+0000] {standard_task_runner.py:55} INFO - Started process 13380 to run task
[2023-04-12T14:04:01.077+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T14:03:00+00:00', '--job-id', '7008', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpiy_h1oub']
[2023-04-12T14:04:01.078+0000] {standard_task_runner.py:83} INFO - Job 7008: Subtask id_2
[2023-04-12T14:04:01.123+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T14:03:00+00:00 [running]> on host b518195edd5e
[2023-04-12T14:04:01.181+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T14:03:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T14:03:00+00:00
[2023-04-12T14:04:01.182+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T14:04:01.183+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T14:04:01.190+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T14:04:01.351+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T14:04:01.352+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T14:04:01.352+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T14:04:01.352+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T14:04:01.353+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T14:04:01.353+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T14:04:01.354+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T14:04:01.363+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T14:04:01.366+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T140300, start_date=20230412T140401, end_date=20230412T140401
[2023-04-12T14:04:01.377+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7008 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 13380)
[2023-04-12T14:04:01.410+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T14:04:01.424+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
