[2023-04-11T19:42:03.878+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T19:36:00+00:00 [queued]>
[2023-04-11T19:42:03.886+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T19:36:00+00:00 [queued]>
[2023-04-11T19:42:03.886+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T19:42:03.887+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-11T19:42:03.887+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T19:42:03.901+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 19:36:00+00:00
[2023-04-11T19:42:03.904+0000] {standard_task_runner.py:55} INFO - Started process 2907 to run task
[2023-04-11T19:42:03.906+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T19:36:00+00:00', '--job-id', '1500', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp7aw_3r7i']
[2023-04-11T19:42:03.907+0000] {standard_task_runner.py:83} INFO - Job 1500: Subtask id_2
[2023-04-11T19:42:03.954+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T19:36:00+00:00 [running]> on host b518195edd5e
[2023-04-11T19:42:04.009+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T19:36:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T19:36:00+00:00
[2023-04-11T19:42:04.010+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T19:42:04.011+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T19:42:04.017+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T19:42:04.145+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-11T19:42:04.145+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-11T19:42:04.146+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-11T19:42:04.146+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-11T19:42:04.147+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-11T19:42:04.147+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-11T19:42:04.148+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-11T19:42:04.156+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-11T19:42:04.159+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T193600, start_date=20230411T194203, end_date=20230411T194204
[2023-04-11T19:42:04.170+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1500 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 2907)
[2023-04-11T19:42:04.199+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T19:42:04.213+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
