[2023-04-12T04:00:04.845+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T03:44:00+00:00 [queued]>
[2023-04-12T04:00:04.854+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T03:44:00+00:00 [queued]>
[2023-04-12T04:00:04.854+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:00:04.855+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-12T04:00:04.855+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:00:04.869+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 03:44:00+00:00
[2023-04-12T04:00:04.873+0000] {standard_task_runner.py:55} INFO - Started process 22315 to run task
[2023-04-12T04:00:04.875+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T03:44:00+00:00', '--job-id', '3990', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpbholkzql']
[2023-04-12T04:00:04.876+0000] {standard_task_runner.py:83} INFO - Job 3990: Subtask id_2
[2023-04-12T04:00:04.925+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T03:44:00+00:00 [running]> on host b518195edd5e
[2023-04-12T04:00:04.983+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T03:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T03:44:00+00:00
[2023-04-12T04:00:04.984+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T04:00:04.985+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T04:00:04.991+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T04:00:05.147+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T04:00:05.148+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T04:00:05.148+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T04:00:05.148+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T04:00:05.149+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T04:00:05.149+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T04:00:05.151+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T04:00:05.161+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T04:00:05.165+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T034400, start_date=20230412T040004, end_date=20230412T040005
[2023-04-12T04:00:05.176+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3990 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 22315)
[2023-04-12T04:00:05.207+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T04:00:05.221+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
