[2023-04-14T14:57:25.084+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:51:00+00:00 [queued]>
[2023-04-14T14:57:25.093+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:51:00+00:00 [queued]>
[2023-04-14T14:57:25.094+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:57:25.094+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-14T14:57:25.095+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:57:25.109+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-14 14:51:00+00:00
[2023-04-14T14:57:25.116+0000] {standard_task_runner.py:55} INFO - Started process 1569 to run task
[2023-04-14T14:57:25.118+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-14T14:51:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpk1wqunu3']
[2023-04-14T14:57:25.120+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask id_2
[2023-04-14T14:57:25.170+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:51:00+00:00 [running]> on host 6f8cd9778af0
[2023-04-14T14:57:25.231+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:51:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T14:51:00+00:00
[2023-04-14T14:57:25.232+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T14:57:25.234+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-14T14:57:25.245+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T14:57:27.323+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:57:27.324+0000] {subprocess.py:93} INFO - --DEBUG: __file__:     /opt/***/src/news_comments_crawlers/crawlers/config/Constants.py
[2023-04-14T14:57:27.324+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:57:27.325+0000] {subprocess.py:93} INFO - -- Session Object : Good to go.
[2023-04-14T14:57:27.325+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:57:27.326+0000] {subprocess.py:93} INFO - -- Log Folder: Good to go.
[2023-04-14T14:57:27.326+0000] {subprocess.py:93} INFO - []
[2023-04-14T14:57:27.328+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-14T14:57:27.328+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 11, in <module>
[2023-04-14T14:57:27.329+0000] {subprocess.py:93} INFO -     from Functions import *
[2023-04-14T14:57:27.329+0000] {subprocess.py:93} INFO -   File "<fstring>", line 1
[2023-04-14T14:57:27.330+0000] {subprocess.py:93} INFO -     (USE_CACHE=)
[2023-04-14T14:57:27.330+0000] {subprocess.py:93} INFO -               ^
[2023-04-14T14:57:27.330+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-14T14:57:27.489+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-14T14:57:27.498+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-14T14:57:27.502+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230414T145100, start_date=20230414T145725, end_date=20230414T145727
[2023-04-14T14:57:27.513+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 100 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 1569)
[2023-04-14T14:57:27.545+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T14:57:27.561+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
